# Asking Questions about Countries

### Getting started with SQL

Run the next cell to set up your environment and load the country data.

In [18]:
# all of your notebooks and homework using SQL are going to start something like this
import warnings
warnings.filterwarnings('ignore')
%load_ext sql

from sols1 import *

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Once you have the SQL extension loaded you need to connect to the database using a connection URL and the magic syntax in the cell below. Change the username  "mattp01" to your own username then run the cell.

In [19]:
%%sql postgresql://aljamo01:@localhost/world

'Connected: aljamo01@world'

We will answer the following questions and more using the SQL claues

* select
* from
* where
* order by
* limit

For each problem delete the "# YOUR CODE HERE" line and also delete "raise NotImplementedError()". Insert prior to your SQL statement:
* "%%sql"

### List all the data about all counties in the continent Africa.

In [21]:
%%sql
SELECT *
FROM country
WHERE continent='Africa'
--country.query(" == 'Africa'").head(10)
;

58 rows affected.

[('DZA', 'Algeria', 'Africa', 'Northern Africa', 2381740.0, 1962, 31471000, 69.7, Decimal('49982.00'), Decimal('46966.00'), 'Al-Jaza\x92ir/Algérie', 'Republic', 'Abdelaziz Bouteflika', 35, 'DZ'),
 ('AGO', 'Angola', 'Africa', 'Central Africa', 1246700.0, 1975, 12878000, 38.3, Decimal('6648.00'), Decimal('7984.00'), 'Angola', 'Republic', 'José Eduardo dos Santos', 56, 'AO'),
 ('BEN', 'Benin', 'Africa', 'Western Africa', 112622.0, 1960, 6097000, 50.2, Decimal('2357.00'), Decimal('2141.00'), 'Bénin', 'Republic', 'Mathieu Kérékou', 187, 'BJ'),
 ('BWA', 'Botswana', 'Africa', 'Southern Africa', 581730.0, 1966, 1622000, 39.3, Decimal('4834.00'), Decimal('4935.00'), 'Botswana', 'Republic', 'Festus G. Mogae', 204, 'BW'),
 ('BFA', 'Burkina Faso', 'Africa', 'Western Africa', 274000.0, 1960, 11937000, 46.7, Decimal('2425.00'), Decimal('2201.00'), 'Burkina Faso', 'Republic', 'Blaise Compaoré', 549, 'BF'),
 ('BDI', 'Burundi', 'Africa', 'Eastern Africa', 27834.0, 1962, 6695000, 46.2, Decimal('903.00'), Decimal('982.00'), 'Burundi/Uburundi', 'Republic', 'Pierre Buyoya', 552, 'BI'),
 ('DJI', 'Djibouti', 'Africa', 'Eastern Africa', 23200.0, 1977, 638000, 50.8, Decimal('382.00'), Decimal('373.00'), 'Djibouti/Jibuti', 'Republic', 'Ismail Omar Guelleh', 585, 'DJ'),
 ('EGY', 'Egypt', 'Africa', 'Northern Africa', 1001450.0, 1922, 68470000, 63.3, Decimal('82710.00'), Decimal('75617.00'), 'Misr', 'Republic', 'Hosni Mubarak', 608, 'EG'),
 ('ERI', 'Eritrea', 'Africa', 'Eastern Africa', 117600.0, 1993, 3850000, 55.8, Decimal('650.00'), Decimal('755.00'), 'Ertra', 'Republic', 'Isayas Afewerki [Isaias Afwerki]', 652, 'ER'),
 ('ZAF', 'South Africa', 'Africa', 'Southern Africa', 1221040.0, 1910, 40377000, 51.1, Decimal('116729.00'), Decimal('129092.00'), 'South Africa', 'Republic', 'Thabo Mbeki', 716, 'ZA'),
 ('ETH', 'Ethiopia', 'Africa', 'Eastern Africa', 1104300.0, -1000, 62565000, 45.2, Decimal('6353.00'), Decimal('6180.00'), 'YeItyop´iya', 'Republic', 'Negasso Gidada', 756, 'ET'),
 ('GAB', 'Gabon', 'Africa', 'Central Africa', 267668.0, 1960, 1226000, 50.1, Decimal('5493.00'), Decimal('5279.00'), 'Le Gabon', 'Republic', 'Omar Bongo', 902, 'GA'),
 ('GMB', 'Gambia', 'Africa', 'Western Africa', 11295.0, 1965, 1305000, 53.2, Decimal('320.00'), Decimal('325.00'), 'The Gambia', 'Republic', 'Yahya Jammeh', 904, 'GM'),
 ('GHA', 'Ghana', 'Africa', 'Western Africa', 238533.0, 1957, 20212000, 57.4, Decimal('7137.00'), Decimal('6884.00'), 'Ghana', 'Republic', 'John Kufuor', 910, 'GH'),
 ('GIN', 'Guinea', 'Africa', 'Western Africa', 245857.0, 1958, 7430000, 45.6, Decimal('2352.00'), Decimal('2383.00'), 'Guinée', 'Republic', 'Lansana Conté', 926, 'GN'),
 ('GNB', 'Guinea-Bissau', 'Africa', 'Western Africa', 36125.0, 1974, 1213000, 49.0, Decimal('293.00'), Decimal('272.00'), 'Guiné-Bissau', 'Republic', 'Kumba Ialá', 927, 'GW'),
 ('CMR', 'Cameroon', 'Africa', 'Central Africa', 475442.0, 1960, 15085000, 54.8, Decimal('9174.00'), Decimal('8596.00'), 'Cameroun/Cameroon', 'Republic', 'Paul Biya', 1804, 'CM'),
 ('CPV', 'Cape Verde', 'Africa', 'Western Africa', 4033.0, 1975, 428000, 68.9, Decimal('435.00'), Decimal('420.00'), 'Cabo Verde', 'Republic', 'António Mascarenhas Monteiro', 1859, 'CV'),
 ('KEN', 'Kenya', 'Africa', 'Eastern Africa', 580367.0, 1963, 30080000, 48.0, Decimal('9217.00'), Decimal('10241.00'), 'Kenya', 'Republic', 'Daniel arap Moi', 1881, 'KE'),
 ('CAF', 'Central African Republic', 'Africa', 'Central Africa', 622984.0, 1960, 3615000, 44.0, Decimal('1054.00'), Decimal('993.00'), 'Centrafrique/Bê-Afrîka', 'Republic', 'Ange-Félix Patassé', 1889, 'CF'),
 ('COM', 'Comoros', 'Africa', 'Eastern Africa', 1862.0, 1975, 578000, 60.0, Decimal('4401.00'), Decimal('4361.00'), 'Komori/Comores', 'Republic', 'Azali Assoumani', 2295, 'KM'),
 ('COG', 'Congo', 'Africa', 'Central Africa', 342000.0, 1960, 2943000, 47.4, Decimal('2108.00'), Decimal('2287.00'), 'Congo', 'Republic', 'Denis Sassou-Nguesso', 2296, 'CG'),
 ('COD', 'Congo, The Democratic Republic of the', 'Africa', 'Central Africa', 2344860.0, 1960, 51654000, 48.8, Decimal('6964.00'), Decimal('2474.00'), 'République Démocratique du Congo', 'Republic', 'Joseph Kabila', 2298, 'CD'),
 ('LSO', 'Lesotho', 'Africa', 'Southern Africa', 30355.0, 1966, 2153000, 50.8, Decimal('1061.00'), Decimal('1161.00'), 'Lesotho', 'Constitutional Monarchy', 'Letsie III', 2437, 'LS'),
 ('LBR', 'Liberia', 'Africa', 'Western Africa', 111369.0, 1847, 3154000, 51.0, Decimal('2012.00'), None, 'Liberia', 'Republic', 'Charles Taylor', 2440, 'LR'),
 ('LBY', 'Libyan Arab Jamahiriya', 'Africa', 'Northern Africa', 1759540.0, 1951, 5605000, 75.5, Decimal('44806.00'), Decimal('40562.00'), 'Libiya', 'Socialistic State', 'Muammar al-Qadhafi', 2441, 'LY'),
 ('ESH', 'Western Sahara', 'Africa', 'Northern Africa', 266000.0, None, 293000, 49.8, Decimal('60.00'), None, 'As-Sahrawiya', 'Occupied by Marocco', 'Mohammed Abdel Aziz', 2453, 'EH'),
 ('MDG', 'Madagascar', 'Africa', 'Eastern Africa', 587041.0, 1960, 15942000, 55.0, Decimal('3750.00'), Decimal('3545.00'), 'Madagasikara/Madagascar', 'Federal Republic', 'Didier Ratsiraka', 2455, 'MG'),
 ('MWI', 'Malawi', 'Africa', 'Eastern Africa', 118484.0, 1964, 10925000, 37.6, Decimal('1687.00'), Decimal('2527.00'), 'Malawi', 'Republic', 'Bakili Muluzi', 2462, 'MW'),
 ('MLI', 'Mali', 'Africa', 'Western Africa', 1240190.0, 1960, 11234000, 46.7, Decimal('2642.00'), Decimal('2453.00'), 'Mali', 'Republic', 'Alpha Oumar Konaré', 2482, 'ML'),
 ('MAR', 'Morocco', 'Africa', 'Northern Africa', 446550.0, 1956, 28351000, 69.1, Decimal('36124.00'), Decimal('33514.00'), 'Al-Maghrib', 'Constitutional Monarchy', 'Mohammed VI', 2486, 'MA'),
 ('MRT', 'Mauritania', 'Africa', 'Western Africa', 1025520.0, 1960, 2670000, 50.8, Decimal('998.00'), Decimal('1081.00'), 'Muritaniya/Mauritanie', 'Republic', 'Maaouiya Ould Sid´Ahmad Taya', 2509, 'MR'),
 ('MUS', 'Mauritius', 'Africa', 'Eastern Africa', 2040.0, 1968, 1158000, 71.0, Decimal('4251.00'), Decimal('4186.00'), 'Mauritius', 'Republic', 'Cassam Uteem', 2511, 'MU'),
 ('MYT', 'Mayotte', 'Africa', 'Eastern Africa', 373.0, None, 149000, 59.5, Decimal('0.00'), None, 'Mayotte', 'Territorial Collectivity of France', 'Jacques Chirac', 2514, 'YT'),
 ('MOZ', 'Mozambique', 'Africa', 'Eastern Africa', 801590.0, 1975, 19680000, 37.5, Decimal('2891.00'), Decimal('2711.00'), 'Moçambique', 'Republic', 'Joaquím A. Chissano', 2698, 'MZ'),
 ('NAM', 'Namibia', 'Africa', 'Southern Africa', 824292.0, 1990, 1726000, 42.5, Decimal('3101.00'), Decimal('3384.00'), 'Namibia', 'Republic', 'Sam Nujoma', 2726, 'NA'),
 ('NER', 'Niger', 'Africa', 'Western Africa', 1267000.0, 1960, 10730000, 41.3, Decimal('1706.00'), Decimal('1580.00'), 'Niger', 'Republic', 'Mamadou Tandja', 2738, 'NE'),
 ('NGA', 'Nigeria', 'Africa', 'Western Africa', 923768.0, 1960, 111506000, 51.6, Decimal('65707.00'), Decimal('58623.00'), 'Nigeria', 'Federal Republic', 'Olusegun Obasanjo', 2754, 'NG'),
 ('CIV', 'Côte d\x92Ivoire', 'Africa', 'Western Africa', 322463.0, 1960, 14786000, 45.2, Decimal('11345.00'), Decimal('10285.00'), 'Côte d\x92Ivoire', 'Republic', 'Laurent Gbagbo', 2814, 'CI'),
 ('GNQ', 'Equatorial Guinea', 'Africa', 'Central Africa', 28051.0, 1968, 453000, 53.6, Decimal('283.00'), Decimal('542.00'), 'Guinea Ecuatorial', 'Republic', 'Teodoro Obiang Nguema Mbasogo', 2972, 'GQ'),
 ('REU', 'Réunion', 'Africa', 'Eastern Africa', 2510.0, None, 699000, 72.7, Decimal('8287.00'), Decimal('7988.00'), 'Réunion', 'Overseas Department of France', 'Jacques Chirac', 3017, 'RE'),
 ('RWA', 'Rwanda', 'Africa', 'Eastern Africa', 26338.0, 1962, 7733000, 39.3, Decimal('2036.00'), Decimal('1863.00'), 'Rwanda/Urwanda', 'Republic', 'Paul Kagame', 3047, 'RW'),
 ('SHN', 'Saint Helena', 'Africa', 'Western Africa', 314.0, None, 6000, 76.8, Decimal('0.00'), None, 'Saint Helena', 'Dependent Territory of the UK', 'Elisabeth II', 3063, 'SH'),
 ('ZMB', 'Zambia', 'Africa', 'Eastern Africa', 752618.0, 1964, 9169000, 37.2, Decimal('3377.00'), Decimal('3922.00'), 'Zambia', 'Republic', 'Frederick Chiluba', 3162, 'ZM'),
 ('STP', 'Sao Tome and Principe', 'Africa', 'Central Africa', 964.0, 1975, 147000, 65.3, Decimal('6.00'), None, 'São Tomé e Príncipe', 'Republic', 'Miguel Trovoada', 3172, 'ST'),
 ('SEN', 'Senegal', 'Africa', 'Western Africa', 196722.0, 1960, 9481000, 62.2, Decimal('4787.00'), Decimal('4542.00'), 'Sénégal/Sounougal', 'Republic', 'Abdoulaye Wade', 3198, 'SN'),
 ('SYC', 'Seychelles', 'Africa', 'Eastern Africa', 455.0, 1976, 77000, 70.4, Decimal('536.00'), Decimal('539.00'), 'Sesel/Seychelles', 'Republic', 'France-Albert René', 3206, 'SC'),
 ('SLE', 'Sierra Leone', 'Africa', 'Western Africa', 71740.0, 1961, 4854000, 45.3, Decimal('746.00'), Decimal('858.00'), 'Sierra Leone', 'Republic', 'Ahmed Tejan Kabbah', 3207, 'SL'),
 ('SOM', 'Somalia', 'Africa', 'Eastern Africa', 637657.0, 1960, 10097000, 46.2, Decimal('935.00'), None, 'Soomaaliya', 'Republic', 'Abdiqassim Salad Hassan', 3214, 'SO'),
 ('SDN', 'Sudan', 'Africa', 'Northern Africa', 2505810.0, 1956, 29490000, 56.6, Decimal('10162.00'), None, 'As-Sudan', 'Islamic Republic', 'Omar Hassan Ahmad al-Bashir', 3225, 'SD'),
 ('SWZ', 'Swaziland', 'Africa', 'Southern Africa', 17364.0, 1968, 1008000, 40.4, Decimal('1206.00'), Decimal('1312.00'), 'kaNgwane', 'Monarchy', 'Mswati III', 3244, 'SZ'),
 ('TZA', 'Tanzania', 'Africa', 'Eastern Africa', 883749.0, 1961, 33517000, 52.3, Decimal('8005.00'), Decimal('7388.00'), 'Tanzania', 'Republic', 'Benjamin William Mkapa', 3306, 'TZ'),
 ('TGO', 'Togo', 'Africa', 'Western Africa', 56785.0, 1960, 4629000, 54.7, Decimal('1449.00'), Decimal('1400.00'), 'Togo', 'Republic', 'Gnassingbé Eyadéma', 3332, 'TG'),
 ('TCD', 'Chad', 'Africa', 'Central Africa', 1284000.0, 1960, 7651000, 50.5, Decimal('1208.00'), Decimal('1102.00'), 'Tchad/Tshad', 'Republic', 'Idriss Déby', 3337, 'TD'),
 ('TUN', 'Tunisia', 'Africa', 'Northern Africa', 163610.0, 1956, 9586000, 73.7, Decimal('20026.00'), Decimal('18898.00'), 'Tunis/Tunisie', 'Republic', 'Zine al-Abidine Ben Ali', 3349, 'TN'),
 ('UGA', 'Uganda', 'Africa', 'Eastern Africa', 241038.0, 1962, 21778000, 42.9, Decimal('6313.00'), Decimal('6887.00'), 'Uganda', 'Republic', 'Yoweri Museveni', 3425, 'UG'),
 ('ZWE', 'Zimbabwe', 'Africa', 'Eastern Africa', 390757.0, 1980, 11669000, 37.8, Decimal('5951.00'), Decimal('8670.00'), 'Zimbabwe', 'Republic', 'Robert G. Mugabe', 4068, 'ZW'),
 ('IOT', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa', 78.0, None, 0, 0.0, Decimal('0.00'), None, 'British Indian Ocean Territory', 'Dependent Territory of the UK', 'Elisabeth II', None, 'IO')]

In [12]:

checker_1S(_)

Error! Results are not the same length. I was expecting 18 rows and your result has 58 rows.

AssertionError:

###  List only the country name and region for the countries in the Middle East region.

In [28]:
%%sql
SELECT name,region
FROM country
WHERE region='Middle East'
--country.query(" == 'Africa'").head(10)
;

18 rows affected.

[('United Arab Emirates', 'Middle East'),
 ('Armenia', 'Middle East'),
 ('Azerbaijan', 'Middle East'),
 ('Bahrain', 'Middle East'),
 ('Georgia', 'Middle East'),
 ('Iraq', 'Middle East'),
 ('Israel', 'Middle East'),
 ('Yemen', 'Middle East'),
 ('Jordan', 'Middle East'),
 ('Kuwait', 'Middle East'),
 ('Cyprus', 'Middle East'),
 ('Lebanon', 'Middle East'),
 ('Oman', 'Middle East'),
 ('Qatar', 'Middle East'),
 ('Saudi Arabia', 'Middle East'),
 ('Syria', 'Middle East'),
 ('Turkey', 'Middle East'),
 ('Palestine', 'Middle East')]

In [ ]:

checker_2S(_)

### Show the country name and life expectancy of the 5 countries with the longest life expectancy.

In [29]:
%%sql
SELECT name,lifeexpectancy
FROM country
order by lifeexpectancy DESC
limit 5 
;

5 rows affected.

[('Andorra', 83.5),
 ('Macao', 81.6),
 ('San Marino', 81.1),
 ('Japan', 80.7),
 ('Singapore', 80.1)]

In [ ]:

checker_3S(_)


### Show the country name, population, region, continent and gnp of the 8 countries with the largest gnp.

In [31]:
%%sql
SELECT name, population, region, continent, gnp
FROM country
order by gnp DESC
limit 8
;

8 rows affected.

[('United States', 278357000, 'North America', 'North America', Decimal('8510700.00')),
 ('Japan', 126714000, 'Eastern Asia', 'Asia', Decimal('3787042.00')),
 ('Germany', 82164700, 'Western Europe', 'Europe', Decimal('2133367.00')),
 ('France', 59225700, 'Western Europe', 'Europe', Decimal('1424285.00')),
 ('United Kingdom', 59623400, 'British Islands', 'Europe', Decimal('1378330.00')),
 ('Italy', 57680000, 'Southern Europe', 'Europe', Decimal('1161755.00')),
 ('China', 1277558000, 'Eastern Asia', 'Asia', Decimal('982268.00')),
 ('Brazil', 170115000, 'South America', 'South America', Decimal('776739.00'))]

In [ ]:

checker_4S(_)

### Show all of the distinct forms of government.

In [37]:
%%sql
SELECT distinct governmentform
FROM country
;

35 rows affected.

[('Monarchy',),
 ('Socialistic Republic',),
 ('Federal Republic',),
 ('Overseas Department of France',),
 ('Constitutional Monarchy',),
 ('Special Administrative Region of China',),
 ('Part of Denmark',),
 ('Administrated by the UN',),
 ('Republic',),
 ('Islamic Republic',),
 ('US Territory',),
 ('Monarchy (Emirate)',),
 ('Dependent Territory of the US',),
 ('Co-administrated',),
 ('Dependent Territory of the UK',),
 ('Constitutional Monarchy, Federation',),
 ('Nonmetropolitan Territory of France',),
 ('Territory of Australia',),
 ('Nonmetropolitan Territory of The Netherlands',),
 ('Constitutional Monarchy (Emirate)',),
 ('Occupied by Marocco',),
 ('Territorial Collectivity of France',),
 ('Dependent Territory of Norway',),
 ('Nonmetropolitan Territory of New Zealand',),
 ('Monarchy (Sultanate)',),
 ("People'sRepublic",),
 ('Parliamentary Coprincipality',),
 ('Commonwealth of the US',),
 ('Islamic Emirate',),
 ('Socialistic State',),
 ('Parlementary Monarchy',),
 ('Autonomous Area',),
 ('Federation',),
 ('Emirate Federation',),
 ('Independent Church State',)]

In [35]:

checker_5S(_)

Error! You have a different number of columns than expected.

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Show all of the distinct regions of the world.

In [38]:
%%sql
SELECT distinct region
FROM country
;

25 rows affected.

[('Micronesia/Caribbean',),
 ('Southern Africa',),
 ('Australia and New Zealand',),
 ('Southeast Asia',),
 ('Southern Europe',),
 ('Northern Africa',),
 ('Antarctica',),
 ('Nordic Countries',),
 ('Central Africa',),
 ('Micronesia',),
 ('Polynesia',),
 ('Western Europe',),
 ('Western Africa',),
 ('Caribbean',),
 ('Melanesia',),
 ('North America',),
 ('Eastern Europe',),
 ('Eastern Africa',),
 ('Middle East',),
 ('Southern and Central Asia',),
 ('British Islands',),
 ('Central America',),
 ('South America',),
 ('Baltic Countries',),
 ('Eastern Asia',)]

In [ ]:

checker_6S(_)

### List the country name and gnp of all of the countries that have a government form of "Monarchy".

In [40]:
%%sql 
SELECT name, gnp 
FROM country
WHERE governmentform= 'Monarchy'
;

5 rows affected.

[('Bhutan', Decimal('372.00')),
 ('Qatar', Decimal('9472.00')),
 ('Saudi Arabia', Decimal('137635.00')),
 ('Swaziland', Decimal('1206.00')),
 ('Tonga', Decimal('146.00'))]

In [ ]:

checker_7S(_)

### List the country name, governmentform and population of the countries that are any kind of Monarchy (hint: study the output from the question above to see all the types of Monarchies. There are 7 in this data).

In [44]:
%%sql 
SELECT name,governmentform, population
FROM country
WHERE governmentform like '%Monarchy%'
;

43 rows affected.

[('Netherlands', 'Constitutional Monarchy', 15864000),
 ('Antigua and Barbuda', 'Constitutional Monarchy', 68000),
 ('Australia', 'Constitutional Monarchy, Federation', 18886000),
 ('Bahamas', 'Constitutional Monarchy', 307000),
 ('Bahrain', 'Monarchy (Emirate)', 617000),
 ('Barbados', 'Constitutional Monarchy', 270000),
 ('Belgium', 'Constitutional Monarchy, Federation', 10239000),
 ('Belize', 'Constitutional Monarchy', 241000),
 ('Bhutan', 'Monarchy', 2124000),
 ('United Kingdom', 'Constitutional Monarchy', 59623400),
 ('Brunei', 'Monarchy (Sultanate)', 328000),
 ('Spain', 'Constitutional Monarchy', 39441700),
 ('Grenada', 'Constitutional Monarchy', 94000),
 ('Jamaica', 'Constitutional Monarchy', 2583000),
 ('Japan', 'Constitutional Monarchy', 126714000),
 ('Jordan', 'Constitutional Monarchy', 5083000),
 ('Cambodia', 'Constitutional Monarchy', 11168000),
 ('Canada', 'Constitutional Monarchy, Federation', 31147000),
 ('Kuwait', 'Constitutional Monarchy (Emirate)', 1972000),
 ('Lesotho', 'Constitutional Monarchy', 2153000),
 ('Liechtenstein', 'Constitutional Monarchy', 32300),
 ('Luxembourg', 'Constitutional Monarchy', 435700),
 ('Malaysia', 'Constitutional Monarchy, Federation', 22244000),
 ('Morocco', 'Constitutional Monarchy', 28351000),
 ('Monaco', 'Constitutional Monarchy', 34000),
 ('Nepal', 'Constitutional Monarchy', 23930000),
 ('Norway', 'Constitutional Monarchy', 4478500),
 ('Oman', 'Monarchy (Sultanate)', 2542000),
 ('Papua New Guinea', 'Constitutional Monarchy', 4807000),
 ('Qatar', 'Monarchy', 599000),
 ('Sweden', 'Constitutional Monarchy', 8861400),
 ('Saint Kitts and Nevis', 'Constitutional Monarchy', 38000),
 ('Saint Lucia', 'Constitutional Monarchy', 154000),
 ('Saint Vincent and the Grenadines', 'Constitutional Monarchy', 114000),
 ('Solomon Islands', 'Constitutional Monarchy', 444000),
 ('Samoa', 'Parlementary Monarchy', 180000),
 ('Saudi Arabia', 'Monarchy', 21607000),
 ('Swaziland', 'Monarchy', 1008000),
 ('Denmark', 'Constitutional Monarchy', 5330000),
 ('Thailand', 'Constitutional Monarchy', 61399000),
 ('Tonga', 'Monarchy', 99000),
 ('Tuvalu', 'Constitutional Monarchy', 12000),
 ('New Zealand', 'Constitutional Monarchy', 3862000)]

In [ ]:

checker_8S(_)

### List the country name and gnp of the countries in Southeast Asia with population less than 5 million.

In [45]:
%%sql 
SELECT name, gnp 
FROM country
WHERE region= 'Southeast Asia' and population < 5000000
;

3 rows affected.

[('Brunei', Decimal('11705.00')),
 ('East Timor', Decimal('0.00')),
 ('Singapore', Decimal('86503.00'))]

In [ ]:

checker_9S(_)

### List the country names, gnp, and population where the (current) gnp is more than the old gnp.

In [46]:
%%sql 
SELECT name, gnp, population
FROM country
WHERE gnp > gnpold
;

115 rows affected.

[('Netherlands', Decimal('371362.00'), 15864000),
 ('Albania', Decimal('3205.00'), 3401200),
 ('Algeria', Decimal('49982.00'), 31471000),
 ('Antigua and Barbuda', Decimal('612.00'), 68000),
 ('United Arab Emirates', Decimal('37966.00'), 2441000),
 ('Argentina', Decimal('340238.00'), 37032000),
 ('Armenia', Decimal('1813.00'), 3520000),
 ('Aruba', Decimal('828.00'), 103000),
 ('Azerbaijan', Decimal('4127.00'), 7734000),
 ('Bahamas', Decimal('3527.00'), 307000),
 ('Bahrain', Decimal('6366.00'), 617000),
 ('Bangladesh', Decimal('32852.00'), 129155000),
 ('Barbados', Decimal('2223.00'), 270000),
 ('Belgium', Decimal('249704.00'), 10239000),
 ('Belize', Decimal('630.00'), 241000),
 ('Benin', Decimal('2357.00'), 6097000),
 ('Bermuda', Decimal('2328.00'), 65000),
 ('Bolivia', Decimal('8571.00'), 8329000),
 ('United Kingdom', Decimal('1378330.00'), 59623400),
 ('Virgin Islands, British', Decimal('612.00'), 21000),
 ('Bulgaria', Decimal('12178.00'), 8190900),
 ('Burkina Faso', Decimal('2425.00'), 11937000),
 ('Cayman Islands', Decimal('1263.00'), 38000),
 ('Costa Rica', Decimal('10226.00'), 4023000),
 ('Djibouti', Decimal('382.00'), 638000),
 ('Dominica', Decimal('256.00'), 71000),
 ('Dominican Republic', Decimal('15846.00'), 8495000),
 ('Ecuador', Decimal('19770.00'), 12646000),
 ('Egypt', Decimal('82710.00'), 68470000),
 ('El Salvador', Decimal('11863.00'), 6276000),
 ('Spain', Decimal('553233.00'), 39441700),
 ('Ethiopia', Decimal('6353.00'), 62565000),
 ('Gabon', Decimal('5493.00'), 1226000),
 ('Georgia', Decimal('6064.00'), 4968000),
 ('Ghana', Decimal('7137.00'), 20212000),
 ('Guam', Decimal('1197.00'), 168000),
 ('Guatemala', Decimal('19008.00'), 11385000),
 ('Guinea-Bissau', Decimal('293.00'), 1213000),
 ('Haiti', Decimal('3459.00'), 8222000),
 ('Honduras', Decimal('5333.00'), 6485000),
 ('India', Decimal('447114.00'), 1013662000),
 ('Iran', Decimal('195746.00'), 67702000),
 ('Ireland', Decimal('75921.00'), 3775100),
 ('Iceland', Decimal('8255.00'), 279000),
 ('Italy', Decimal('1161755.00'), 57680000),
 ('Austria', Decimal('211860.00'), 8091800),
 ('Jamaica', Decimal('6871.00'), 2583000),
 ('Yemen', Decimal('6041.00'), 18112000),
 ('Jordan', Decimal('7526.00'), 5083000),
 ('Cameroon', Decimal('9174.00'), 15085000),
 ('Cape Verde', Decimal('435.00'), 428000),
 ('Kazakstan', Decimal('24375.00'), 16223000),
 ('Central African Republic', Decimal('1054.00'), 3615000),
 ('China', Decimal('982268.00'), 1277558000),
 ('Comoros', Decimal('4401.00'), 578000),
 ('Congo, The Democratic Republic of the', Decimal('6964.00'), 51654000),
 ('Greece', Decimal('120724.00'), 10545700),
 ('Croatia', Decimal('20208.00'), 4473000),
 ('Cyprus', Decimal('9333.00'), 754700),
 ('Latvia', Decimal('6398.00'), 2424200),
 ('Lebanon', Decimal('17121.00'), 3282000),
 ('Libyan Arab Jamahiriya', Decimal('44806.00'), 5605000),
 ('Liechtenstein', Decimal('1119.00'), 32300),
 ('Lithuania', Decimal('10692.00'), 3698500),
 ('Luxembourg', Decimal('16321.00'), 435700),
 ('Madagascar', Decimal('3750.00'), 15942000),
 ('Mali', Decimal('2642.00'), 11234000),
 ('Malta', Decimal('3512.00'), 380200),
 ('Morocco', Decimal('36124.00'), 28351000),
 ('Martinique', Decimal('2731.00'), 395000),
 ('Mauritius', Decimal('4251.00'), 1158000),
 ('Mexico', Decimal('414972.00'), 98881000),
 ('Mongolia', Decimal('1043.00'), 2662000),
 ('Mozambique', Decimal('2891.00'), 19680000),
 ('Myanmar', Decimal('180375.00'), 45611000),
 ('Niger', Decimal('1706.00'), 10730000),
 ('Nigeria', Decimal('65707.00'), 111506000),
 ('Côte d\x92Ivoire', Decimal('11345.00'), 14786000),
 ('Oman', Decimal('16904.00'), 2542000),
 ('Pakistan', Decimal('61289.00'), 156483000),
 ('Panama', Decimal('9131.00'), 2856000),
 ('Portugal', Decimal('105954.00'), 9997600),
 ('Puerto Rico', Decimal('34100.00'), 3869000),
 ('Poland', Decimal('151697.00'), 38653600),
 ('Qatar', Decimal('9472.00'), 599000),
 ('France', Decimal('1424285.00'), 59225700),
 ('French Polynesia', Decimal('818.00'), 235000),
 ('Réunion', Decimal('8287.00'), 699000),
 ('Romania', Decimal('38158.00'), 22455500),
 ('Rwanda', Decimal('2036.00'), 7733000),
 ('Germany', Decimal('2133367.00'), 82164700),
 ('Senegal', Decimal('4787.00'), 9481000),
 ('Slovakia', Decimal('20594.00'), 5398700),
 ('Slovenia', Decimal('19756.00'), 1987800),
 ('Sri Lanka', Decimal('15706.00'), 18827000),
 ('Finland', Decimal('121914.00'), 5171300),
 ('Suriname', Decimal('870.00'), 417000),
 ('Switzerland', Decimal('264478.00'), 7160400),
 ('Syria', Decimal('65984.00'), 16125000),
 ('Tajikistan', Decimal('1990.00'), 6188000),
 ('Tanzania', Decimal('8005.00'), 33517000),
 ('Denmark', Decimal('174099.00'), 5330000),
 ('Togo', Decimal('1449.00'), 4629000),
 ('Trinidad and Tobago', Decimal('6232.00'), 1295000),
 ('Chad', Decimal('1208.00'), 7651000),
 ('Czech Republic', Decimal('55017.00'), 10278100),
 ('Tunisia', Decimal('20026.00'), 9586000),
 ('Turkey', Decimal('210721.00'), 66591000),
 ('Turkmenistan', Decimal('4397.00'), 4459000),
 ('Hungary', Decimal('48267.00'), 10043200),
 ('Uruguay', Decimal('20831.00'), 3337000),
 ('Vanuatu', Decimal('261.00'), 190000),
 ('Venezuela', Decimal('95023.00'), 24170000),
 ('Estonia', Decimal('5328.00'), 1439200),
 ('United States', Decimal('8510700.00'), 278357000)]

In [ ]:

checker_10S(_)